version: 0.1

phases:
  install:
    commands:
      - echo installing node.js
      - curl -sL https://deb.nodesource.com/setup_14.x | bash -
      - apt-get install -y nodejs
      - sudo npm install

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: ./